### ISSUE TITLE
Seriously, the licence needs fixed.

### ISSUE THREAD

**Issue by VegaDeftwing** [lllyasviel/PaintingLight#11]
There's been interest in adding this to Krita, but given people will use Krita for commercial works it's necessary to know how this project can be used. The Apache Licences in this repo would permit it; however, the copyright claim on the project's page would not.

**Comment by VegaDeftwing** [comment]
Re: #8

**Comment by VegaDeftwing** [comment]
Also, since this project seems to be getting very little attention from the two contributors with active commits, @bobbens I thought I'd tag you too.

**Comment by lllyasviel** [comment]
OK.&nbsp; I have self-assigned this issue.&nbsp; I will keep Apache lisence and remove other lisences.&nbsp;



---Original---

**Comment by VegaDeftwing** [comment]
Also, of note, there are now 78 forks of this repo with the Apache2.0 license in this strange limbo and this project has nearly 500 stars. That makes this a very awkward situation and my "Im not a lawyer" advise would be that, if you don't think youd want to spend legal fees defending your license, to just commit to the more permissive license aut right.

Thank you to all of you for this project, I hope that this technology can make it's way into creative software, weather it be FOSS or commercial soon.

**Comment by lllyasviel** [comment]
Thank you for the suggestions. I will take these into consideration and revise the lisence.&nbsp;



---Original---

**Comment by gceboh** [comment]
[zyddnys/PaintLight](https://github.com/zyddnys/PaintLight) seems to be an **unofficial C++ re-implementation**, which may be useful. (since [krita](https://github.com/KDE/krita) is written in C++.)

(Unfortunately, I failed to compile it on my computer.)

**Comment by hirokic5** [comment]
@lllyasviel thanks you for great projects & repository!!!  
By the way, the line 3 in code/ProjectPaintingLight.py still says **Non-commercial usage only**. 
I would appreciate it if you check that.
thanks
