### ISSUE TITLE
Question: When is the photoshop plugin coming out?

### ISSUE THREAD

**Issue by AndreyRGW** [lllyasviel/PaintingLight#18]
I'm personally looking forward to seeing when you release it. I'd like to know a tentative timeline. Or have you abandoned the idea?

**Comment by lllyasviel** [comment]
We made several attempts, but without much success. Nevertheless, this item is still on our to-do list with medium priority, and clearly, we have not abandoned it. Thank you for remind this item and we will continue doing our best.
