### ISSUE TITLE
Important Installation Note & Bug Report about Memory Usage

### ISSUE THREAD

**Issue by gceboh** [lllyasviel/PaintingLight#2]
First of all, thank you for providing such an awesome research  project!

Important Installation Note: (code version:[07d12f2](https://github.com/lllyasviel/PaintingLight/commit/07d12f243e542e8491c26623279ffd47a838daf3))
1.For Windows user, Python version must be `Python 3.6 x86-64`.
Higher python version doesn't support [the pre-compiled whl file](https://github.com/lllyasviel/PaintingLight/blob/master/code/Rtree-0.9.3-cp36-cp36m-win_amd64.whl). You will receive the following error info if incorrect python version is used:

> Rtree-0.9.3-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

<br/>
2. If you get the following error:

> ImportError: 'load_model' requires h5py.

then you need to install h5py:
`pip install h5py`

<br/>
3.  [BUG] The 'ray intersecting process' sometimes consumes more than 5GB of physical memory, which will lead to crash with a "Memory Error" info. 

> (MemoryError: Unable to allocate XXX. MiB for an array with shape (XXXXXX, 3) and data type float64)

In addition, it sometimes (about 70% probability) causes **the whole operating system to become frozen** (without giving any error information, just keeps showing `Begin ray intersecting ...`). The reason may be that all the  physical memory is used up. (And the physical memory usage of python.exe increase too fast so that windows memory management doesn't have enough time to swap it to the virtual memory.) When my computer is frozen, I can't move the cursor or open the Task Manager, and the keyboard does not respond. The only solution is to forcely reboot the computer by pressing the power button. It's quite a strange bug!

**[Workaround]**
I finally found a workaround to prevent my computer from being frozen. Use [Process Governor](https://github.com/lowleveldesign/process-governor) to limit the memory usage of 'python.exe'. Command:
`procgov64 --maxmem 5000M python default.py image.png`

After I use the tool, though the  "memory error" persists, my computer won't get frozen!

**Hardware and software environment:**
OS: Win 8.1 x64
Physical memory: 8GB
Pyembree not installed.

<br/>

**I know it's quite HARD to develop such a complex research project.** Hope the above information could benefit other users and help the authors to fix the bug.

<br/><br/>

**[Update_2020-06-09]**
1. Solved. This has been added to `readme.md`.
2. Solved. This has been added to `readme.md`.
3. It seems that this system frozen bug ONLY occurs **when physical memory is equal to or less than 8GB**. (For default 512px image examples.)

<br/>

**A BETTER solution is [Here](https://github.com/lllyasviel/PaintingLight/issues/2#issuecomment-641184908)!** (This solution can prevent the system from being frozen.)

**Comment by lllyasviel** [comment]
Well. What is the resolution of your image? If the image is very big then it may require large memory.

**Comment by gceboh** [comment]
Thank you for your rapid reply.
<br/>
1.It seems that many examples will consumes more than 5GB of physical memory. 
For example,`example002.py`.
After it displayed `Begin ray intersecting ...`, the physical memory usage growed slowly in the first 2 minutes (about 300MB), but **it growed rapidly in the last few seconds before crash** (increase 1GB per second). The following picture is a physical memory usage capture by [ProcessHacker](https://github.com/processhacker/processhacker).

![memory usage curve](https://user-images.githubusercontent.com/29419865/80296394-6a41a380-87ad-11ea-8d8f-fb1975f70adc.png)

2. I modified `imgs\002.jpg`, resizing it from "768x512"  to "192x128" (25% of the original image size). **But strangely, still got the memory error**:

> Begin ray intersecting ...
Traceback (most recent call last):
  File "example002.py", line 23, in <module>
    light_color_blue, enabling_multiple_channel_effects)
  File "D:\{project path}\PaintingLight-200225\code\ProjectPaintingLight.py", line 151, in run
    index_tri, index_ray, locations = intersector.intersects_id(start, direction, return_locations=True, multiple_hits=True)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\ray\ray_triangle.py", line 57, in intersects_id
    triangles_normal=self.mesh.face_normals)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\ray\ray_triangle.py", line 194, in ray_triangle_id
    line_directions=line_directions)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\intersections.py"
, line 384, in planes_lines
    on_plane += line_origins[valid]
MemoryError: Unable to allocate 432. MiB for an array with shape (18881118, 3) and data type float64

**Comment by gceboh** [comment]
1.I again resized `imgs\002.jpg` from "768x512" to **"96x64"** (12.5% of the original image size). 
The memory limit is 5GB. But strangely, still got the memory error. 
(I use an old Intel HD Graphics card, and Pyembree not installed. Maybe this has some impact.)

2.Another customized image with the size 1022x1443 works normally without error info. It seems that  **the memory usage is related to not only the resolution, but also the image content**.

I guess maybe it is hard to fix this problem. Perhaps the "trimesh" utility is mainly designed for Server usage, not for low-end PC usage. **It doesn't matter a lot, this is still an excellent project.**

> Begin ray intersecting ...
Traceback (most recent call last):
  File "example002.py", line 23, in <module>
    light_color_blue, enabling_multiple_channel_effects)
  File "D:\(project path)\PaintingLight-200225\code\ProjectPaintingLight.py", line 151, in run
    index_tri, index_ray, locations = intersector.intersects_id(start, direction, return_locations=True, multiple_hits=True)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\ray\ray_triangle.py", line 57, in intersects_id
    triangles_normal=self.mesh.face_normals)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\ray\ray_triangle.py", line 194, in ray_triangle_id
    line_directions=line_directions)
  File "E:\Programs\VirtualEnvs\paint_lighting\lib\site-packages\trimesh\intersections.py", line 383, in planes_lines
    on_plane = line_directions[valid] * distance.reshape((-1, 1))
MemoryError: Unable to allocate 450. MiB for an array with shape (19678658, 3) and data type float64

**Comment by lllyasviel** [comment]
Well, if low-res image also yield out-of-memory then is is out of my knowledge. I will spend some period of time to check it. BTW all examples works on my PC with 16GB ram and 980M. My opinion is that if it requires 5 GB mem then it is just OK because 5 GB mem is not very large for an data science project. Nevertheless, if it gives out-of-memory error frequently, I will try to fix it.

**Comment by gceboh** [comment]
Thanks for reply.
Yes, **it is NOT a commercial product, it's enough for academic research!**

**Comment by gceboh** [comment]
This issue and the workaround is provided for those users whose physical memory is equal or less than 8GB.

**Comment by gceboh** [comment]
I found out that this bug may be caused by a **Memory leak bug** of the `Trimesh` package. [Related issue](https://github.com/mikedh/trimesh/issues/155#issuecomment-382637559). 
<br/>
And a possible **Simple Solution** is to install `Pyembree` . (I didn't install it previously.)
Currently I don't have enough time to validate this solution. But hope this would help other users!

**Comment by gceboh** [comment]
**[Solution for rendering full-sized (512px) image with 8GB physical memory]**
1. Install Pyembree. (Perhaps it can turbo the process.)
2. Set Windows Virtual Memory to 8192MB to **prevent “out of memory” error**. Note that DO NOT select “System managed size”. 
Now total memory is 8GB + 8GB=16GB. (But this can't prevent the system from being freezed.)
3. Run `python example002.py` (No need for “Process Governor” this time, because process's memory will exceed the amount of physical memory).
The rendering process cost **17 minutes** on my computer (including 10 minutes of freezing the whole system, during which the cursor couldn’t move). After the rendering process, the system isn't freezed and memory usage drop to 100MB.

**Comment by gceboh** [comment]
The above solution seems not so practical. But during debuging this problem, I found that I made a mistake when resizing the image. Following [lllyasviel‘s advice](https://github.com/lllyasviel/PaintingLight/issues/2#issuecomment-618914866), I change `002.jpg` 's resolution (change the file content). **But I didn’t notice that there is a resizing code in `ProjectPaintingLight.py`!** So the correct way is to modify the code. lllyasviel‘s advice works!


**[Practical solution for users with 8GB physical memory]**
1. Modify `ProjectPaintingLight.py` at [line 129](https://github.com/lllyasviel/PaintingLight/blob/112a040f964d9ef947b961fdb56543c406950cbe/code/ProjectPaintingLight.py#L129) . **Resize all input image to 256 pixels**, because 512 pixels cosumes too much memory. 
Thanks to lllyasviel‘s advice ,this modification can **significantly reduce the memory usage and time 
 consumed.**

Original code:
```
# Some pre-processing to resize images and remove input JPEG artifacts.
raw_image = min_resize(image, 512)
raw_image = run_srcnn(raw_image)
raw_image = min_resize(raw_image, 512)
```
After modification:
```
 # Some pre-processing to resize images and remove input JPEG artifacts.
 raw_image = min_resize(image, 256)# change
 raw_image = run_srcnn(raw_image)
 raw_image = min_resize(raw_image, 256)# change
```
 
2. Run the following command: 
`procgov64 --maxmem 5000M python example002.py`
([Process Governor](https://github.com/lowleveldesign/process-governor) is for preventing the system from being freezed)

For `example002`, it will consume about 2GB of physical memory. The rendering time is about 30 seconds (with ot without Pyembree). **During the rendering process, the system won't be freezed any more!**

**Comment by lllyasviel** [comment]
What? example002.py only needs 1 second in my laptop with Pyembree at 512 resolution. 

I am using I7 cpu + 980M gpu.
