### ISSUE TITLE
ImportError: `load_model` requires h5py.

### ISSUE THREAD

**Issue by My12123** [lllyasviel/PaintingLight#20]
![2023-01-19_11-32-13](https://user-images.githubusercontent.com/49092250/213393148-b20714b9-cea7-4d3f-a50a-2224b294e741.png)

**Comment by SanjayGhanagiri** [comment]
@My12123 I might be late,  but try to install this specific verion of h5py : pip install h5py==2.10.0. This should fix the issue.
