### ISSUE TITLE
Small advice about readme.md

### ISSUE THREAD

**Issue by gceboh** [lllyasviel/PaintingLight#3]
Small Advice about `readme.md`:
1. At readme.md [line 33](https://github.com/lllyasviel/PaintingLight/blame/f305740bbf46ff6c8359e2fefb39a224155b14d7/README.md#L33):
I suggest change "super accurate" to "Image super resolution".

2. About the license statement: `Licensed by Style2Paints for noncommercial research use only. `
Currently the license statement only appears in the [project page](https://lllyasviel.github.io/PaintingLight/), but not in `readme.md`. **I suggest add the License statement to  `readme.md`.**
(Note that the above license statement is **contrary** with [the license file lies in the root dir](https://github.com/lllyasviel/PaintingLight/blob/master/LICENSE). The Apache License 2.0 [allows for "Commercial use"](https://choosealicense.com/licenses/apache-2.0/). Probably the root license  file is wrong.)

3. By the way, [style2paints](https://github.com/lllyasviel/style2paints) also seems to suffer from [the license file](https://github.com/lllyasviel/style2paints/blob/master/LICENSE) problem.

Hope these are helpful!

**Comment by gceboh** [comment]
PS: if a user click a repo's [license file link](https://github.com/lllyasviel/PaintingLight/blob/master/LICENSE), GitHub will show in the top that this repo allows for "Commercial use". What's more, the license is shown in the search result and top bar of the repo's main page.

**Comment by lllyasviel** [comment]
Thank you for advice. I will tune the license and expositions later.

**Comment by kwea123** [comment]
currently all github's default licenses allow commercial use...

**Comment by gceboh** [comment]
Non-commercial open source project example:
https://github.com/CMU-Perceptual-Computing-Lab/openpose#license
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/92c7f7c4d7f6e6a2c24e85ee24a77a8c55bd4693/LICENSE#L3

For reference only, hope these may be useful.
