### ISSUE TITLE
not an issue really but really have no idea where to ask 

### ISSUE THREAD

**Issue by pokeheadroom** [lllyasviel/PaintingLight#7]
how exactly do i save my results? i've been loving playing arround with this but i just wish i knew how to save some angles since some of these look very impressive

**Comment by kwea123** [comment]
You can add a key event at the end of `ProjectPaintingLight.py` like this:
https://github.com/kwea123/PaintingLight/blob/28abb5c8946ed5a714fc4f1ee6df011300949e0d/code/ProjectPaintingLight.py#L212-L218
It will save the right part (lighted image) when you press 's' key.

**Comment by pokeheadroom** [comment]
thank you so much
