### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Deevad** [lllyasviel/PaintingLight#8]
Hey, 

The artwork here: 
https://github.com/lllyasviel/PaintingLight/blob/master/index_files/paintlight_title.jpg
published on 
https://lllyasviel.github.io/PaintingLight/
is an artwork traced from my art and a copy of my OC and design of Shichimi... source comic page for proof:
https://www.peppercarrot.com/0_sources/0ther/artworks/hi-res/2016-08-16_comic-page_from-A-to-Z_tutorial_by-David-Revoy.jpg

But! I publish this art under Creative Commons attribution 4.0 International to "David Revoy"; it allows you to do use it, do derivation, etc. I just request here you write somewhere "artwork traced by \<insertnamehere\> from an artwork by David Revoy under CC-BY license, www.peppercarrot.com" . Thanks!

**Comment by lllyasviel** [comment]
Thank you for this notification and we have added the updated credits. We are also currently double checking all other materials to ensure the consistency of image licenses.

**Comment by lllyasviel** [comment]
I am closing this issue now. Feel free to request for re-opening this issue if some further modifications are needed.

**Comment by Deevad** [comment]
Perfect attribution :+1: Thank you very much for such a quick edit!

**Comment by gceboh** [comment]
another paper copy:
https://esslab.jp/en/publications/

**Comment by gceboh** [comment]
If it is inconvenient to contact the server administrator, please ignore my reply.

**Comment by Deevad** [comment]
Hey @gceboh , it's ok. :wink: 
I understand the paper was copied/hosted on various platform and it's hard to update them. No need to bother admin with it, imo.
I just wanted the attribution because the paper went viral, and I received many feedback that my characters were appearing but my name wasn't mentioned. (also on Youtube video comments, on a video where Saffron retraced appear as on panel 2 here https://www.peppercarrot.com/0_sources/ep22_The-Voting-System/low-res/en_Pepper-and-Carrot_by-David-Revoy_E22P09.jpg ).

**Comment by lllyasviel** [comment]
Yes, and we will also update other paper distributions. Also, that 

    "Saffron retraced appear as on panel 2" 

is in fact from this post 

    "https://www.davidrevoy.com/article330/making-of-episode-22-the-voting-system"

which is found from 

    "https://www.davidrevoy.com/index.php?tag/cc-by"   .

And, if Deevad mean this video 

    "https://www.youtube.com/watch?v=ihYsJpibNRU&t"   , 

the credits of 

    "Pepper and Carrot, David Revoy - https://www.davidrevoy.com/tag/cc-by" 

is already in the YouTube video description, and those 

    "feedback that my characters were appearing but my name wasn't mentioned (in the video)" 

might because the YouTube video description is not very eye-catching. Nonetheless, this description has already done a good job.

Finally, we would like to thank the author of Pepper and Carrot so much for those great CC-by materials.

**Comment by Deevad** [comment]
Ha good for the Youtube description! 

> "https://www.davidrevoy.com/index.php?tag/cc-by"

Yep, that's my blog. You can also find many line-art in HD here: https://www.peppercarrot.com/en/static6/sources&page=inks , raw pencil scan here https://www.peppercarrot.com/en/static6/sources&page=original , and everything that compose the Pepper&Carrot webcomic here https://www.peppercarrot.com/en/static6/sources (all in CC-By). On my blog, www.davidrevoy.com, I keep the making-of/tutorial aspect of the project (the "behind the scene").

> Finally, we would like to thank the author(s) of Pepper and Carrot so much for those great CC-by materials.

My pleasure! I'm David Revoy (nickname 'Deevad'), the artist and scenarist, thank you for using the artworks for science! I usually like to blog post about them under this tag: https://www.davidrevoy.com/tag/paper , but I'm a bit late to cover recent one :smile:
